export default [
    {
        img1: "https://images.prothomalo.com/prothomalo-english%2F2022-09%2Feb415716-2ff8-4578-893f-e2a3ccfbbcf6%2FPM_Hasina.jpg?auto=format%2Ccompress&format=webp&w=940&dpr=1.0",
        p0: "Bangladesh in World Media",
        p1: "PM Hasina invites UK businesses to avail investment opportunities in Bangladesh",
        p2: "Chief minister of India's West Bengal Mamata Banerjee with prime minister Sheikh Hasina in Kolkata on 22 November, 2019, File photo",
        p3: "PM Hasina invites UK businesses to avail investment opportunities in Bangladesh",
        p4: "Sheikh Hasina paid tribute to the contributions of Lord Bilimoria’s late father army during Bangladesh’s War of Independence",
        p5: "West Bengal chief minister Mamata Banerjee on Thursday lambasted the BJP-led Centre for not inviting her to meet visiting Bangladesh prime minister Sheikh Hasina.",
        p6: "Addressing her party members at Netaji Indoor Stadium in Kolkata, Banerjee said, “This is the first time the prime minister of Bangladesh came to India and did not come to Bengal despite her desire to meet me.”",
        img2: "https://tpc.googlesyndication.com/simgad/1055748145008676036",
        p7: "“I do not know why they (BJP) are so angry. They also did not let me go to many places including Chicago and China to attend events. While BJP attends invitations globally, they stop us from attending the same. We ask: How long will you continue your autocracy?” Mamata said.",
        p8: "Soon after arriving in New Delhi on Monday, Bangladesh prime minister met his Indian counterpart Narendra Modi and held bilateral talks to review and further strengthen the relationship between both countries at Hyderabad House, following which seven MoUs have been signed between the two countries.",
        img3: "https://tpc.googlesyndication.com/simgad/12394082693396877238",
        p9: "Bangladesh prime minister Sheikh Hasina, during the joint press statement at Hyderabad House, expressed hope that the issue of Teesta water sharing with India will be resolved soon.",
        p10: "“The two countries have resolved many outstanding issues and we hope that all outstanding issues, including Teesta water-sharing treaty, would be concluded at an early date,” she said in a joint statement with PM Narendra Modi.",
        img4: "https://tpc.googlesyndication.com/simgad/11886436064207034381"
    },
    {
        img1: "https://images.prothomalo.com/prothomalo-english%2F2022-07%2Fc289da93-d68f-4823-a481-b57063903a28%2F422672_01_02.jpg?rect=0%2C0%2C3872%2C2178&auto=format%2Ccompress&fmt=webp&format=webp&w=940&dpr=1.0",
        p0: "International",
        p1: "PM Hasina invites UK businesses to avail investment opportunities in Bangladesh",
        p2: "Chief minister of India's West Bengal Mamata Banerjee with prime minister Sheikh Hasina in Kolkata on 22 November, 2019, File photo",
        p3: "PM Hasina invites UK businesses to avail investment opportunities in Bangladesh",
        p4: "Sheikh Hasina paid tribute to the contributions of Lord Bilimoria’s late father army during Bangladesh’s War of Independence",
        p5: "West Bengal chief minister Mamata Banerjee on Thursday lambasted the BJP-led Centre for not inviting her to meet visiting Bangladesh prime minister Sheikh Hasina.",
        p6: "Addressing her party members at Netaji Indoor Stadium in Kolkata, Banerjee said, “This is the first time the prime minister of Bangladesh came to India and did not come to Bengal despite her desire to meet me.”",
        img2: "https://tpc.googlesyndication.com/simgad/1055748145008676036",
        p7: "“I do not know why they (BJP) are so angry. They also did not let me go to many places including Chicago and China to attend events. While BJP attends invitations globally, they stop us from attending the same. We ask: How long will you continue your autocracy?” Mamata said.",
        p8: "Soon after arriving in New Delhi on Monday, Bangladesh prime minister met his Indian counterpart Narendra Modi and held bilateral talks to review and further strengthen the relationship between both countries at Hyderabad House, following which seven MoUs have been signed between the two countries.",
        img3: "https://tpc.googlesyndication.com/simgad/12394082693396877238",
        p9: "Bangladesh prime minister Sheikh Hasina, during the joint press statement at Hyderabad House, expressed hope that the issue of Teesta water sharing with India will be resolved soon.",
        p10: "“The two countries have resolved many outstanding issues and we hope that all outstanding issues, including Teesta water-sharing treaty, would be concluded at an early date,” she said in a joint statement with PM Narendra Modi.",
        img4: "https://tpc.googlesyndication.com/simgad/11886436064207034381"
    },
    {
        img1: "https://images.prothomalo.com/prothomalo-english%2F2022-09%2F0ce85f4f-d284-48c6-88d1-2b5c3950f7a3%2Fprothomalo_bangla_2021_09_7ecc685c_63b0_4e13_8948_067076ba4ad1_salauddin__13_.webp?rect=71%2C0%2C759%2C506&auto=format%2Ccompress&fmt=webp&format=webp&w=320&dpr=1.0",
        p0: "foregin policy",
        p1: "PM Hasina invites UK businesses to avail investment opportunities in Bangladesh",
        p2: "Chief minister of India's West Bengal Mamata Banerjee with prime minister Sheikh Hasina in Kolkata on 22 November, 2019, File photo",
        p3: "PM Hasina invites UK businesses to avail investment opportunities in Bangladesh",
        p4: "Sheikh Hasina paid tribute to the contributions of Lord Bilimoria’s late father army during Bangladesh’s War of Independence",
        p5: "West Bengal chief minister Mamata Banerjee on Thursday lambasted the BJP-led Centre for not inviting her to meet visiting Bangladesh prime minister Sheikh Hasina.",
        p6: "Addressing her party members at Netaji Indoor Stadium in Kolkata, Banerjee said, “This is the first time the prime minister of Bangladesh came to India and did not come to Bengal despite her desire to meet me.”",
        img2: "https://tpc.googlesyndication.com/simgad/1055748145008676036",
        p7: "“I do not know why they (BJP) are so angry. They also did not let me go to many places including Chicago and China to attend events. While BJP attends invitations globally, they stop us from attending the same. We ask: How long will you continue your autocracy?” Mamata said.",
        p8: "Soon after arriving in New Delhi on Monday, Bangladesh prime minister met his Indian counterpart Narendra Modi and held bilateral talks to review and further strengthen the relationship between both countries at Hyderabad House, following which seven MoUs have been signed between the two countries.",
        img3: "https://tpc.googlesyndication.com/simgad/12394082693396877238",
        p9: "Bangladesh prime minister Sheikh Hasina, during the joint press statement at Hyderabad House, expressed hope that the issue of Teesta water sharing with India will be resolved soon.",
        p10: "“The two countries have resolved many outstanding issues and we hope that all outstanding issues, including Teesta water-sharing treaty, would be concluded at an early date,” she said in a joint statement with PM Narendra Modi.",
        img4: "https://tpc.googlesyndication.com/simgad/11886436064207034381"
    },
    {
        img1: "https://images.prothomalo.com/prothomalo-english%2F2022-02%2F6a4763a3-3559-42b6-ae44-12caa16fb047%2FCovid_19_Vaccine.jpg?rect=0%2C0%2C1200%2C800&auto=format%2Ccompress&fmt=webp&format=webp&w=300&dpr=1.0",
        p0: "corona virous world wide",
        p1: "PM Hasina invites UK businesses to avail investment opportunities in Bangladesh",
        p2: "Chief minister of India's West Bengal Mamata Banerjee with prime minister Sheikh Hasina in Kolkata on 22 November, 2019, File photo",
        p3: "PM Hasina invites UK businesses to avail investment opportunities in Bangladesh",
        p4: "Sheikh Hasina paid tribute to the contributions of Lord Bilimoria’s late father army during Bangladesh’s War of Independence",
        p5: "West Bengal chief minister Mamata Banerjee on Thursday lambasted the BJP-led Centre for not inviting her to meet visiting Bangladesh prime minister Sheikh Hasina.",
        p6: "Addressing her party members at Netaji Indoor Stadium in Kolkata, Banerjee said, “This is the first time the prime minister of Bangladesh came to India and did not come to Bengal despite her desire to meet me.”",
        img2: "https://tpc.googlesyndication.com/simgad/1055748145008676036",
        p7: "“I do not know why they (BJP) are so angry. They also did not let me go to many places including Chicago and China to attend events. While BJP attends invitations globally, they stop us from attending the same. We ask: How long will you continue your autocracy?” Mamata said.",
        p8: "Soon after arriving in New Delhi on Monday, Bangladesh prime minister met his Indian counterpart Narendra Modi and held bilateral talks to review and further strengthen the relationship between both countries at Hyderabad House, following which seven MoUs have been signed between the two countries.",
        img3: "https://tpc.googlesyndication.com/simgad/12394082693396877238",
        p9: "Bangladesh prime minister Sheikh Hasina, during the joint press statement at Hyderabad House, expressed hope that the issue of Teesta water sharing with India will be resolved soon.",
        p10: "“The two countries have resolved many outstanding issues and we hope that all outstanding issues, including Teesta water-sharing treaty, would be concluded at an early date,” she said in a joint statement with PM Narendra Modi.",
        img4: "https://tpc.googlesyndication.com/simgad/11886436064207034381"
    },
    {
        img1: "https://images.prothomalo.com/prothomalo-english%2F2020-03%2Fae65b003-13ab-41b3-96e8-18afe4856576%2FCOVID_19.JPG?rect=0%2C0%2C3375%2C2250&auto=format%2Ccompress&fmt=webp&format=webp&w=300&dpr=1.0",
        p0: "covid-19",
        p1: "PM Hasina invites UK businesses to avail investment opportunities in Bangladesh",
        p2: "Chief minister of India's West Bengal Mamata Banerjee with prime minister Sheikh Hasina in Kolkata on 22 November, 2019, File photo",
        p3: "PM Hasina invites UK businesses to avail investment opportunities in Bangladesh",
        p4: "Sheikh Hasina paid tribute to the contributions of Lord Bilimoria’s late father army during Bangladesh’s War of Independence",
        p5: "West Bengal chief minister Mamata Banerjee on Thursday lambasted the BJP-led Centre for not inviting her to meet visiting Bangladesh prime minister Sheikh Hasina.",
        p6: "Addressing her party members at Netaji Indoor Stadium in Kolkata, Banerjee said, “This is the first time the prime minister of Bangladesh came to India and did not come to Bengal despite her desire to meet me.”",
        img2: "https://tpc.googlesyndication.com/simgad/1055748145008676036",
        p7: "“I do not know why they (BJP) are so angry. They also did not let me go to many places including Chicago and China to attend events. While BJP attends invitations globally, they stop us from attending the same. We ask: How long will you continue your autocracy?” Mamata said.",
        p8: "Soon after arriving in New Delhi on Monday, Bangladesh prime minister met his Indian counterpart Narendra Modi and held bilateral talks to review and further strengthen the relationship between both countries at Hyderabad House, following which seven MoUs have been signed between the two countries.",
        img3: "https://tpc.googlesyndication.com/simgad/12394082693396877238",
        p9: "Bangladesh prime minister Sheikh Hasina, during the joint press statement at Hyderabad House, expressed hope that the issue of Teesta water sharing with India will be resolved soon.",
        p10: "“The two countries have resolved many outstanding issues and we hope that all outstanding issues, including Teesta water-sharing treaty, would be concluded at an early date,” she said in a joint statement with PM Narendra Modi.",
        img4: "https://tpc.googlesyndication.com/simgad/11886436064207034381"
    },
    {
        img1: "https://images.prothomalo.com/prothomalo-english%2F2022-09%2Fddd7f3c6-0620-41b4-8d35-eb5da039d894%2F117222_01_02__1_.jpg?rect=144%2C0%2C6137%2C4091&auto=format%2Ccompress&fmt=webp&format=webp&w=300&dpr=1.0",
        p0: "Bangladesh in World Media",
        p1: "PM Hasina invites UK businesses to avail investment opportunities in Bangladesh",
        p2: "Chief minister of India's West Bengal Mamata Banerjee with prime minister Sheikh Hasina in Kolkata on 22 November, 2019, File photo",
        p3: "PM Hasina invites UK businesses to avail investment opportunities in Bangladesh",
        p4: "Sheikh Hasina paid tribute to the contributions of Lord Bilimoria’s late father army during Bangladesh’s War of Independence",
        p5: "West Bengal chief minister Mamata Banerjee on Thursday lambasted the BJP-led Centre for not inviting her to meet visiting Bangladesh prime minister Sheikh Hasina.",
        p6: "Addressing her party members at Netaji Indoor Stadium in Kolkata, Banerjee said, “This is the first time the prime minister of Bangladesh came to India and did not come to Bengal despite her desire to meet me.”",
        img2: "https://tpc.googlesyndication.com/simgad/1055748145008676036",
        p7: "“I do not know why they (BJP) are so angry. They also did not let me go to many places including Chicago and China to attend events. While BJP attends invitations globally, they stop us from attending the same. We ask: How long will you continue your autocracy?” Mamata said.",
        p8: "Soon after arriving in New Delhi on Monday, Bangladesh prime minister met his Indian counterpart Narendra Modi and held bilateral talks to review and further strengthen the relationship between both countries at Hyderabad House, following which seven MoUs have been signed between the two countries.",
        img3: "https://tpc.googlesyndication.com/simgad/12394082693396877238",
        p9: "Bangladesh prime minister Sheikh Hasina, during the joint press statement at Hyderabad House, expressed hope that the issue of Teesta water sharing with India will be resolved soon.",
        p10: "“The two countries have resolved many outstanding issues and we hope that all outstanding issues, including Teesta water-sharing treaty, would be concluded at an early date,” she said in a joint statement with PM Narendra Modi.",
        img4: "https://tpc.googlesyndication.com/simgad/11886436064207034381"
    },
    {
        img1: "https://images.prothomalo.com/prothomalo-english%2F2022-09%2F9e5b33af-e2a5-4de1-a856-8c8a804dc247%2FPhoto_of_Zhang_Ping_an.jpg?rect=0%2C0%2C2532%2C1688&auto=format%2Ccompress&fmt=webp&format=webp&w=300&dpr=1.0",
        p0: "Bangladesh in World Media",
        p1: "PM Hasina invites UK businesses to avail investment opportunities in Bangladesh",
        p2: "Chief minister of India's West Bengal Mamata Banerjee with prime minister Sheikh Hasina in Kolkata on 22 November, 2019, File photo",
        p3: "PM Hasina invites UK businesses to avail investment opportunities in Bangladesh",
        p4: "Sheikh Hasina paid tribute to the contributions of Lord Bilimoria’s late father army during Bangladesh’s War of Independence",
        p5: "West Bengal chief minister Mamata Banerjee on Thursday lambasted the BJP-led Centre for not inviting her to meet visiting Bangladesh prime minister Sheikh Hasina.",
        p6: "Addressing her party members at Netaji Indoor Stadium in Kolkata, Banerjee said, “This is the first time the prime minister of Bangladesh came to India and did not come to Bengal despite her desire to meet me.”",
        img2: "https://tpc.googlesyndication.com/simgad/3084827580144585973",
        p7: "“I do not know why they (BJP) are so angry. They also did not let me go to many places including Chicago and China to attend events. While BJP attends invitations globally, they stop us from attending the same. We ask: How long will you continue your autocracy?” Mamata said.",
        p8: "Soon after arriving in New Delhi on Monday, Bangladesh prime minister met his Indian counterpart Narendra Modi and held bilateral talks to review and further strengthen the relationship between both countries at Hyderabad House, following which seven MoUs have been signed between the two countries.",
        img3: "https://tpc.googlesyndication.com/simgad/12394082693396877238",
        p9: "Bangladesh prime minister Sheikh Hasina, during the joint press statement at Hyderabad House, expressed hope that the issue of Teesta water sharing with India will be resolved soon.",
        p10: "“The two countries have resolved many outstanding issues and we hope that all outstanding issues, including Teesta water-sharing treaty, would be concluded at an early date,” she said in a joint statement with PM Narendra Modi.",
        img4: "https://tpc.googlesyndication.com/simgad/11886436064207034381"
    }

];